### ISSUE TITLE
md 파일 네이밍을 바꿔주시면 Code 쪽에서 바로 보여서 더 편합니다.

### ISSUE THREAD

**Issue by stzhyegeun** [stzjihwan/test_rjh#1]
Assignment02 폴더에 **추가 기능 방안.md** 파일이 있는데 이름을 README.md로 바꾸면 Code 뷰에서 바로 표시되서 더 쉽게 볼 수 있지 않을까요?

**Comment by stzjihwan** [comment]
아하 감사합니다 ^^
